version: '3.8'

services:
  web:
    build: .
    volumes:
      - $PWD/stream_app:/app
    ports:
      - 8000:8000
    links:
      - db

  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_PASSWORD=django
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - $PWD/PGDATA:/var/lib/postgresql/data

volumes:
  PGDATA:
    driver: local
    driver_opts:
       type: none
       o: bind
       device: $PWD/PGDATA
