version: '3.8'

services:
  web:
    environment:
      ENV: DEV
      OME_HOST: 192.168.1.198
      KEY: aKq#1kj
    build: .
    volumes:
      - $PWD/stream_app:/app
    ports:
      - 8000:8000
    links:
      - db
      - oven

  oven:
    image: airensoft/ovenmediaengine:0.15.10
    ports:
      - 8081:8081
      - 1935:1935
      - 3333:3333
      # - 3334:3334
      - 9000:9000

    environment: 
      - OME_ORIGIN_PORT=9000
      - OME_RTMP_PROV_PORT=1935
      - OME_LLHLS_STREAM_PORT=3333
      # - OME_LLHLS_STREAM_TLS_PORT=3334
      - OME_API_PORT=8081

    volumes:
    - ./origin_conf:/opt/ovenmediaengine/bin/origin_conf


  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_PASSWORD=django
    volumes:
      - PGDATA:/var/lib/postgresql/data
      - $PWD/DATABASE:/db

volumes:
  PGDATA:
