version: '3.8'

services:
  web:
    environment:
      ENV: DEV
      OME_HOST: ${OME_HOST}
      OME_POLICY_KEY: ${OME_POLICY_KEY}
      OME_API_TOKEN: ${OME_API_TOKEN}
      OME_VHOST_NAME: ${OME_VHOST_NAME}
      OME_APP_NAME: ${OME_APP_NAME}
    build: .
    volumes:
      - ./stream_app:/app
    ports:
      - 8000:8000
    networks:
      nginx_net:
    restart: unless-stopped
    
  ome:
    image: airensoft/ovenmediaengine:0.15.10
    ports:
      - 8081:8081
      - 1935:1935
      - 3333:3333
      - 9000:9000
    restart: always
    environment: 
      OME_RTMP_PROV_PORT: 1935
      OME_LLHLS_STREAM_PORT: 3333
      OME_API_PORT: 8081
      OME_POLICY_KEY: ${OME_POLICY_KEY}
      OME_API_TOKEN: ${OME_API_TOKEN}
      OME_VHOST_NAME: ${OME_VHOST_NAME}
      OME_APP_NAME: ${OME_APP_NAME}   
    volumes:
      - ./config/origin_conf/Server.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml
    networks:
      nginx_net:

  db:
    image: postgres:latest
    user: postgres
    volumes:
      - PGDATA:/var/lib/postgresql/data
      - ./DATABASE:/db
    networks:
      nginx_net:  
    restart: always

  centrifugo:
    image: centrifugo/centrifugo:v5
    volumes:
      - ./config/centrifugo/:/centrifugo/
    command: centrifugo -c config.json
    ports:
      - 8800:8800
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      nginx_net:
    restart: always
    
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      nginx_net:


volumes:
  PGDATA:

networks:
  nginx_net: