version: '3.8'

services:
  web:
    environment:
      ENV: DEV
    build: .
    volumes:
      - $PWD/stream_app:/app
    ports:
      - 8000:8000
    links:
      - db
      - oven

  oven:
    image: airensoft/ovenmediaengine:0.15.0
    ports:
      - 8081:8081
      - 1935:1935
      - 4000:4000/udp
      - 3333:3333
      - 3334:3334
      - 3478:3478
      - 9000:9000
      - 9999:9999/udp
    volumes:
    - ./origin_conf:/opt/ovenmediaengine/bin/origin_conf
    # command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf
    # restart: always


  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_PASSWORD=django
    volumes:
      - PGDATA:/var/lib/postgresql/data
      - $PWD/DATABASE:/db

volumes:
  PGDATA:
