version: '3.8'

services:
  web:
    environment:
      ENV: DEV
    build: .
    volumes:
      - $PWD/stream_app:/app
    ports:
      - 8000:8000
    links:
      - db
      - oven

  oven:
    image: airensoft/ovenmediaengine:0.15.0
    ports:
      - 8081:8081
      - 1935:1935
      - 4000:4000/udp
      - 3333:3333
      - 3334:3334
      - 3478:3478
      - 9000:9000
      - 9999:9999/udp

    environment:
      - OME_HOST_IP=192.168.1.198
      - OME_ORIGIN_PORT=9000
      - OME_RTMP_PROV_PORT=1935
      - OME_SRT_PROV_PORT=9999
      - OME_LLHLS_STREAM_PORT=3333
      - OME_WEBRTC_SIGNALLING_PORT=3333
      - OME_WEBRTC_TCP_RELAY_PORT=3478
      - OME_WEBRTC_CANDIDATE_PORT=10000-10004/udp
      - OME_API_PORT=8081

    volumes:
    - ./origin_conf:/opt/ovenmediaengine/bin/origin_conf


  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_PASSWORD=django
    volumes:
      - PGDATA:/var/lib/postgresql/data
      - $PWD/DATABASE:/db

volumes:
  PGDATA:
