version: '3.8'

services:

  web:
    environment:
      ENV: STAGE
    build: .
    ports:
      - 8000:8000
    links:
      - db
      - oven
    volumes:
      - STATIC:/app/stream_app/static
      
  oven:
    image: airensoft/ovenmediaengine:0.15.0
    ports:
      - 1935:1935
      - 4000:4000/udp
      - 3333:3333
      - 3334:3334
      - 3478:3478
      - 9000:9000
      - 9999:9999/udp

  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_PASSWORD=django
    volumes:
      - PGDATA:/var/lib/postgresql/data

  proxy:
    build: ./nginx
    links:
      - web
    ports:
      - 80:80
    volumes:
      - STATIC:/app/stream_app/static

volumes:
  PGDATA:
  STATIC:
