version: '3.3'

services:
  web:
    user: 1000:1001
    environment:
      ENV: STAGE
      OME_HOST: ${OME_HOST}
      OME_POLICY_KEY: ${OME_POLICY_KEY}
      OME_API_TOKEN: ${OME_API_TOKEN}
      OME_VHOST_NAME: ${OME_VHOST_NAME}
      OME_APP_NAME: ${OME_APP_NAME}
    build: .
    volumes:
      - ./stream_app:/app
      - STATIC:/app/stream_app/static
    ports:
      - 8000:8000
    networks:
      nginx_net:
    restart: always
    
  ome:
    image: airensoft/ovenmediaengine:0.15.10
    ports:
      - 8081:8081
      - 8082:8082
      - 1935:1935
      - 3333:3333
      - 3334:3334
      - 9000:9000 
    environment: 
      OME_POLICY_KEY: ${OME_POLICY_KEY}
      OME_API_TOKEN: ${OME_API_TOKEN}
      OME_VHOST_NAME: ${OME_VHOST_NAME}
      OME_APP_NAME: ${OME_APP_NAME}   
    volumes:
    - ./config/origin_conf/Server_stage.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml
    - ./cert/conf:/etc/letsencrypt:ro
    networks:
      nginx_net:
    restart: always  

  db:
    image: postgres:latest
    user: postgres
    volumes:
      - PGDATA:/var/lib/postgresql/data
      - ./DATABASE:/db
    networks:
      nginx_net:
    restart: always
  
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - STATIC:/app/stream_app/static
      - ./config/nginx/stage.conf:/etc/nginx/conf.d/default.conf
      - ./cert/conf/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./cert/conf:/etc/letsencrypt:ro
      - ./cert/www:/var/www/certbot:ro
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    networks:
      nginx_net: 
    # restart: unless-stopped   
  
  certbot:
    image: certbot/certbot
    user: 1000:1001
    volumes:
      - ./cert/conf:/etc/letsencrypt:rw
      - ./cert/www:/var/www/certbot:rw
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # command: certonly --webroot --webroot-path=/var/www/certbot/ --email tagabenz@gmail.com --agree-tos --no-eff-email -d dev.lastream.online
    depends_on:
      - proxy  
    networks:
      nginx_net:
    # restart: unless-stopped   

volumes:
  PGDATA:
  STATIC:

networks:
  nginx_net:

