# Generated by Django 4.1 on 2023-03-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.menu'),
        ),
    ]
