# Generated by Django 4.1 on 2023-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_menu_categories_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
