# Generated by Django 4.1 on 2023-03-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_menu_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
