# Generated by Django 4.1 on 2023-04-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_categories_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='img',
        ),
    ]
