# Generated by Django 4.1 on 2023-04-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_categories_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='img',
            field=models.ImageField(null=True, upload_to='svg/'),
        ),
    ]
