# Generated by Django 4.1 on 2023-03-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='obj',
        ),
    ]
