# Generated by Django 4.1 on 2023-04-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dob',
        ),
    ]
