# Generated by Django 4.1 on 2023-07-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_users_cat_users_is_online_users_stream_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='stream_key',
            field=models.TextField(null=True, verbose_name='Ключ трансляции'),
        ),
    ]
