# Generated by Django 4.1 on 2023-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_alter_users_stream_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='stream_key',
            field=models.CharField(max_length=255, null=True, verbose_name='Ключ трансляции'),
        ),
    ]
