# Generated by Django 4.1 on 2023-09-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_alter_users_stream_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_online',
        ),
        migrations.AddField(
            model_name='users',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
