# Generated by Django 4.1 on 2023-10-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_remove_users_cat_remove_users_stream_key_and_more'),
        ('studio', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='studio.studio', verbose_name='Трансляции'),
        ),
    ]
