# Generated by Django 4.1 on 2023-10-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_initial'),
        ('app_users', '0012_users_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='studio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='studio.studio', verbose_name='Трансляции'),
        ),
    ]
