# Generated by Django 4.1 on 2023-10-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0013_alter_users_studio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='studio',
            new_name='stream',
        ),
    ]
