# Generated by Django 4.1 on 2023-10-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_initial'),
        ('app_users', '0014_rename_studio_users_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='stream',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio', verbose_name='Трансляция'),
        ),
    ]
