# Generated by Django 4.1 on 2023-10-31 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_alter_studio_options'),
        ('app_users', '0015_alter_users_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='stream',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio', verbose_name='stream'),
        ),
    ]
