# Generated by Django 4.1 on 2023-11-22 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0016_alter_users_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='follow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
