# Generated by Django 4.1 on 2023-11-22 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0017_users_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='follow',
        ),
        migrations.AddField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='users_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
