# Generated by Django 4.1 on 2023-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='img_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
