# Generated by Django 4.1 on 2023-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs_description_blogs_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='img_url',
        ),
        migrations.AddField(
            model_name='blogs',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='img',
            field=models.ImageField(null=True, upload_to='photos/%Y/%n/%d'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_published',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
