# Generated by Django 4.1 on 2023-05-02 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_online', models.BooleanField(default=False, verbose_name='Он-лайн')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.categories', verbose_name='Категория')),
            ],
        ),
    ]
