# Generated by Django 4.1 on 2023-05-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_url',
            field=models.CharField(max_length=255, null=True, verbose_name='URL трансляции'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menu.categories', verbose_name='Категория'),
        ),
    ]
