# Generated by Django 4.1 on 2023-05-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_stream_stream_url_alter_stream_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='stream_url',
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_key',
            field=models.CharField(max_length=255, null=True, verbose_name='Ключ трансляции'),
        ),
    ]
