# Generated by Django 4.1 on 2023-07-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_stream_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
