# Generated by Django 4.1 on 2023-10-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('studio', '0005_delete_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=255, null=True, verbose_name='Название трансляции')),
                ('stream_key', models.CharField(max_length=255, null=True, verbose_name='Ключ трансляции')),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menu.categories', verbose_name='Категория')),
            ],
        ),
    ]
