# Generated by Django 4.1 on 2023-10-31 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studio',
            options={'verbose_name': 'Трансляции', 'verbose_name_plural': 'Трансляции'},
        ),
    ]
