name: CI
env:
  COMPOSE_ARG: "-f prod.yml -p stream"

on:
  push:
    branches:
      - main

jobs:
  start_project:
    runs-on: self-hosted
    steps:
      - name: Get_code
        uses: actions/checkout@v3
      - name: Build_project
        run: sudo docker-compose ${{ env.COMPOSE_ARG }} build --no-cache
      - name: start_project
        run: sudo docker-compose ${{ env.COMPOSE_ARG }} up -d
