name: CI

on:
  push:
    branches: 
      - main

jobs:
  start_project:
    runs-on: self-hosted
    steps:
      - name: Get_code
        uses: actions/checkout@v3
      - name: Build_project
        run: ls -la
        
