name: Stage deploy
env:
  COMPOSE_ARG: "--env-file .env.stage -f stage.yml"
on:
  push:
    branches:
      - develop 

jobs:
  start_project:
    runs-on: self-hosted
    steps:
      - name: Get_code
        uses: actions/checkout@v3  
      - name: Build_project                                                 
        run: docker compose ${{ env.COMPOSE_ARG }} build --no-cache
      - name: start_project
        run: docker compose ${{ env.COMPOSE_ARG }} up -d
