name: Stage deploy
env:
  COMPOSE_ARG: "-f stage.yml"

on:
  push:
    branches:
      - develop 

jobs:
  start_project:
    runs-on: stage-runner 
    steps:
      - name: Get_code
        uses: actions/checkout@v3  
      - name: Build_project                                                 
        run: docker-compose ${{ env.COMPOSE_ARG }} build --no-cache
      - name: start_project
        run: docker-compose --env-file .env.stage ${{ env.COMPOSE_ARG }} up -d
